### ISSUE TITLE
error parser

### ISSUE THREAD

**Issue by lbenicio** [renatorib/tibia-node-crawler#5]
When i try the command:

`var tibia = require('tibia-node-crawler');`

`tibia.character(command, function (data) {console.log(data)})`

i receive an error from console: 

`/path/to/node/script/node_modules/tibia-node-crawler/src/libs/better.js:79
    .replace('by an')
    ^

TypeError: Cannot read property 'replace' of undefined`

**Comment by renatorib** [comment]
Hey, this project is **abandoned**
Sorry for this :(

**Comment by lbenicio** [comment]
Hi, i noticed that,  shit happens! I managed to keep to project going on! added a series of functions (currently im building a TSWarBot and use your API. By the way, nice work!
